---


include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/docker-image.gitlab-ci.yaml
      - template/website.gitlab-ci.yaml


variables:
  DOCKER_IMAGE_BUILD_TARGET_PLATFORMS: "linux/amd64,linux/arm64"
  DOCKER_IMAGE_PUBLISH_NAME: 'docker-mail'
  DOCKER_IMAGE_PUBLISH_REGISTRY: docker.io/nofusscomputing
  DOCKER_IMAGE_PUBLISH_URL: https://hub.docker.com/r/nofusscomputing/$DOCKER_IMAGE_PUBLISH_NAME

  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/docker-mail.git"
  MY_PROJECT_ID: "33611657"
  PAGES_ENVIRONMENT_PATH: projects/docker-mail/



Compile Dovecot:
  extends: .build_docker_container
  variables:
    DOCKER_DOCKERFILE: dockerfile-compile
    DOCKER_IMAGE_BUILD_TARGET_PLATFORMS: "linux/arm64"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
      allow_failure: true
    - when: never


Website:Stage.Publish:
  stage: publish
  trigger:
    project: nofusscomputing/infrastructure/website
    branch: development
  needs: [ Website.Build ]
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == "development"'
      when: on_success
    - when: never


Website:Deploy.Publish:
  stage: publish
  trigger:
    project: nofusscomputing/infrastructure/website
    branch: development
  needs: [ Website.Build ]
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never