INHERIT: website-template/mkdocs.yml

repo_name: Gitlab-CI
repo_url: https://gitlab.com/nofusscomputing/projects/docker-mail
edit_uri: '/-/ide/project/nofusscomputing/projects/docker-mail/edit/development/-/pages/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Docker E-Mail Server: 

    - projects/docker-mail/index.md

    - projects/docker-mail/dkim.md

    - projects/docker-mail/spf.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

